/**
 * SV Diagrams – 3D Hardware Visualisation (Three.js)
 *
 * Reads diagram-metadata JSON (generated by scripts/generate_diagram_meta.py)
 * and renders an interactive 3D scene with cuboid instances, bundled signal
 * cylinders, group enclosures, and click-to-inspect popups.
 */

import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { CSS2DRenderer, CSS2DObject } from "three/addons/renderers/CSS2DRenderer.js";

/* ─── constants ──────────────────────────────────────────────────────── */

const K = {
  BASE_CUBE: 4,            // base cube side length (units)
  MIN_SCALE: 0.6,          // minimum cuboid scale factor
  MAX_SCALE: 2.2,          // maximum cuboid scale factor
  MIN_GROUP_H: 2,          // minimum height for group enclosures
  CLK_COL: 0x00E676,
  RST_COL: 0xFF5252,
  SIG_COL: 0xFFC107,
  TLM_COL: 0x29B6F6,
  HIER_COL: 0xCE93D8,
  TB_COL: 0x546E7A,
  BUNDLE_RADIUS: 0.18,     // cylinder radius for bundled signals
  BUNDLE_MAX_R: 0.6,       // max bundle cylinder radius
  CAM_DIST: 1.6,           // camera distance multiplier
  HIT_RADIUS: 0.45,        // click hit-zone radius
  LOD_DIST: 120,            // label hide distance
  COMP_OPACITY: 0.10,       // base opacity for composable blocks
  COMP_EDGE_OPACITY: 0.45,  // wireframe edge opacity for composable blocks
};

/* ─── renderer setup ─────────────────────────────────────────────────── */

const canvas = document.getElementById("canvas");
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.setSize(window.innerWidth, window.innerHeight);

const labelRenderer = new CSS2DRenderer();
labelRenderer.setSize(window.innerWidth, window.innerHeight);
labelRenderer.domElement.style.position = "fixed";
labelRenderer.domElement.style.inset = "0";
labelRenderer.domElement.style.pointerEvents = "none";
labelRenderer.domElement.style.zIndex = "50";
document.body.appendChild(labelRenderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x0d0d1a);
scene.fog = new THREE.FogExp2(0x0d0d1a, 0.0025);

const camera = new THREE.PerspectiveCamera(55, window.innerWidth / window.innerHeight, 0.1, 500);
camera.position.set(0, 18, 40);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.08;
controls.autoRotate = false;
controls.autoRotateSpeed = 0.4;

/* ─── lights ─────────────────────────────────────────────────────────── */

scene.add(new THREE.AmbientLight(0xffffff, 0.45));
const sun = new THREE.DirectionalLight(0xffffff, 0.9);
sun.position.set(12, 20, 10);
scene.add(sun);
const fill = new THREE.DirectionalLight(0x8888ff, 0.25);
fill.position.set(-12, -6, -10);
scene.add(fill);

/* ─── grid ───────────────────────────────────────────────────────────── */

const grid = new THREE.GridHelper(100, 50, 0x222244, 0x1a1a33);
grid.position.y = -6;
scene.add(grid);

/* ─── state ──────────────────────────────────────────────────────────── */

let designData = null;            // current design JSON
const clickableObjects = [];      // meshes for raycasting
const objectMeta = new Map();     // mesh → { type, data }
const lodObjects = [];            // { obj, maxDist }
let currentHighlightObjs = [];    // currently highlighted objects
const connCylinders = new Map();  // connKey → { cylinders[], originalColor, conn }

/* ─── DOM refs ───────────────────────────────────────────────────────── */

const $select   = document.getElementById("design-select");
const $title    = document.getElementById("design-title");
const $loading  = document.getElementById("loading-overlay");
const $loadText = document.getElementById("loading-text");
const $overview = document.getElementById("overview");
const $ovTitle  = document.getElementById("overview-title");
const $ovBody   = document.getElementById("overview-body");
const $popup    = document.getElementById("popup");
const $popTitle = document.getElementById("popup-title");
const $popBody  = document.getElementById("popup-body");

/* ─── utility: geometry builders ─────────────────────────────────────── */

function makeLabel(html, className) {
  const el = document.createElement("div");
  el.className = className;
  el.innerHTML = html;
  return new CSS2DObject(el);
}

function solidLine(pts, color) {
  const g = new THREE.BufferGeometry().setFromPoints(pts.map(p => new THREE.Vector3(...p)));
  return new THREE.Line(g, new THREE.LineBasicMaterial({ color }));
}

function dashedLine(pts, color) {
  const g = new THREE.BufferGeometry().setFromPoints(pts.map(p => new THREE.Vector3(...p)));
  const m = new THREE.LineDashedMaterial({ color, dashSize: 0.6, gapSize: 0.3 });
  const l = new THREE.Line(g, m);
  l.computeLineDistances();
  return l;
}

function dashedBox(cx, cy, cz, w, h, d, color) {
  const g = new THREE.BoxGeometry(w, h, d);
  const e = new THREE.EdgesGeometry(g);
  const m = new THREE.LineDashedMaterial({ color, dashSize: 1, gapSize: 0.5, transparent: true, opacity: 0.5 });
  const seg = new THREE.LineSegments(e, m);
  seg.computeLineDistances();
  seg.position.set(cx, cy, cz);
  return seg;
}

/**
 * Create a composable (solid semi-transparent) container block for groups and testbench.
 * These are the "box within box" hierarchy visuals.
 */
function composableBlock(cx, cy, cz, w, h, d, color, depth = 0) {
  const group = new THREE.Group();

  // Opacity decreases with nesting depth (outermost most transparent)
  const opacity = K.COMP_OPACITY + depth * 0.03;

  // Solid semi-transparent face
  const faceGeo = new THREE.BoxGeometry(w, h, d);
  const faceMat = new THREE.MeshLambertMaterial({
    color, transparent: true, opacity,
    side: THREE.DoubleSide, depthWrite: false,
  });
  const mesh = new THREE.Mesh(faceGeo, faceMat);
  mesh.renderOrder = -10 + depth;  // outer first, inner later
  group.add(mesh);

  // Wireframe edges
  const edgeGeo = new THREE.EdgesGeometry(faceGeo);
  const edgeMat = new THREE.LineBasicMaterial({
    color, transparent: true, opacity: K.COMP_EDGE_OPACITY,
  });
  group.add(new THREE.LineSegments(edgeGeo, edgeMat));

  group.position.set(cx, cy, cz);
  return { group, mesh };
}

/**
 * Create an instance cuboid.
 * @param {object} inst  - instance from diagram JSON
 * @param {number} hex   - colour
 * @param {number} scale - overall scale factor
 * @param {object} renderSize - optional {sx, sy, sz} overrides
 */
function instanceCuboid(inst, hex, scale = 1, renderSize) {
  const sx = (renderSize?.sx ?? K.BASE_CUBE) * scale;
  const sy = (renderSize?.sy ?? K.BASE_CUBE) * scale;
  const sz = (renderSize?.sz ?? K.BASE_CUBE) * scale;

  const group = new THREE.Group();

  // solid face
  const faceGeo = new THREE.BoxGeometry(sx, sy, sz);
  const faceMat = new THREE.MeshLambertMaterial({
    color: hex, transparent: true, opacity: 0.55,
  });
  const mesh = new THREE.Mesh(faceGeo, faceMat);
  group.add(mesh);

  // wireframe edges
  const edgeGeo = new THREE.EdgesGeometry(faceGeo);
  const edgeMat = new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.35 });
  group.add(new THREE.LineSegments(edgeGeo, edgeMat));

  const p = inst.position;
  group.position.set(p.x, p.y, p.z);

  // label
  const labelHtml = `${inst.name}<span class="module-type">${inst.module}</span>`;
  const label = makeLabel(labelHtml, "cube-label");
  label.position.set(0, sy / 2 + 1.2, 0);
  group.add(label);
  lodObjects.push({ obj: label, maxDist: K.LOD_DIST });

  // store metadata
  group.userData = { instanceName: inst.name, module: inst.module, scale };
  mesh.userData = group.userData;

  return { group, mesh, sx, sy, sz };
}

/**
 * Create a bundled-signal cylinder between two points.
 */
function bundleCylinder(from, to, color, numSignals) {
  const a = new THREE.Vector3(...from);
  const b = new THREE.Vector3(...to);
  const dir = new THREE.Vector3().subVectors(b, a);
  const len = dir.length();

  // radius proportional to signal count, capped
  const r = Math.min(K.BUNDLE_MAX_R, K.BUNDLE_RADIUS + numSignals * 0.012);

  const geo = new THREE.CylinderGeometry(r, r, len, 8, 1);
  const mat = new THREE.MeshLambertMaterial({
    color, transparent: true, opacity: 0.45,
  });
  const cyl = new THREE.Mesh(geo, mat);

  // position at midpoint, orient along direction
  const mid = new THREE.Vector3().addVectors(a, b).multiplyScalar(0.5);
  cyl.position.copy(mid);

  // align cylinder axis (Y) to direction
  const axis = new THREE.Vector3(0, 1, 0);
  const quat = new THREE.Quaternion().setFromUnitVectors(axis, dir.clone().normalize());
  cyl.setRotationFromQuaternion(quat);

  return cyl;
}

/**
 * Create an invisible hit-zone cylinder for click detection.
 */
function hitZone(from, to) {
  const a = new THREE.Vector3(...from);
  const b = new THREE.Vector3(...to);
  const dir = new THREE.Vector3().subVectors(b, a);
  const len = dir.length();
  const geo = new THREE.CylinderGeometry(K.HIT_RADIUS, K.HIT_RADIUS, len, 6, 1);
  const mat = new THREE.MeshBasicMaterial({ visible: false });
  const cyl = new THREE.Mesh(geo, mat);
  const mid = new THREE.Vector3().addVectors(a, b).multiplyScalar(0.5);
  cyl.position.copy(mid);
  const axis = new THREE.Vector3(0, 1, 0);
  cyl.setRotationFromQuaternion(
    new THREE.Quaternion().setFromUnitVectors(axis, dir.clone().normalize())
  );
  return cyl;
}

/**
 * Compute a bounding box for a set of positioned items.
 */
function computeBounds(items, pad = 4) {
  let xMin = Infinity, xMax = -Infinity;
  let yMin = Infinity, yMax = -Infinity;
  let zMin = Infinity, zMax = -Infinity;
  for (const it of items) {
    const p = it.position ?? it;
    xMin = Math.min(xMin, (p.x ?? 0) - pad);
    xMax = Math.max(xMax, (p.x ?? 0) + pad);
    yMin = Math.min(yMin, (p.y ?? 0) - pad);
    yMax = Math.max(yMax, (p.y ?? 0) + pad);
    zMin = Math.min(zMin, (p.z ?? 0) - pad);
    zMax = Math.max(zMax, (p.z ?? 0) + pad);
  }
  return { xMin, xMax, yMin, yMax, zMin, zMax };
}

/**
 * Route an orthogonal L-shaped connection, with simple obstacle avoidance.
 */
function routeConnection(ax, ay, az, bx, by, bz, obstacles) {
  // Direct line if aligned on X or Z
  if (Math.abs(ax - bx) < 0.5 || Math.abs(az - bz) < 0.5) {
    return [[ax, ay, az], [bx, by, bz]];
  }

  // L-shape: go horizontal then vertical (in XZ plane)
  const cornerY = (ay + by) / 2;
  const midX = (ax + bx) / 2;
  const midZ = (az + bz) / 2;

  // Check if corner route is blocked
  let blocked = false;
  if (obstacles) {
    for (const obs of obstacles) {
      if (Math.abs(bx - obs.x) < obs.hw && Math.abs(az - obs.z) < obs.hh) {
        blocked = true;
        break;
      }
    }
  }

  if (blocked) {
    // Route around: go up, across, down
    const detourY = Math.max(ay, by) + 3;
    return [
      [ax, ay, az],
      [ax, detourY, az],
      [bx, detourY, bz],
      [bx, by, bz],
    ];
  }

  return [
    [ax, ay, az],
    [bx, cornerY, az],
    [bx, by, bz],
  ];
}

/* ─── scene builder ──────────────────────────────────────────────────── */

async function buildScene(designPath) {
  // clear scene — dispose geometry/materials and remove CSS2D label DOM nodes
  scene.traverse((child) => {
    if (child.geometry) child.geometry.dispose();
    if (child.material) {
      if (Array.isArray(child.material)) child.material.forEach(m => m.dispose());
      else child.material.dispose();
    }
    // CSS2DObject appends its element to the labelRenderer container
    if (child.isCSS2DObject && child.element && child.element.parentNode) {
      child.element.parentNode.removeChild(child.element);
    }
  });
  while (scene.children.length > 0) scene.remove(scene.children[0]);
  clickableObjects.length = 0;
  objectMeta.clear();
  lodObjects.length = 0;
  currentHighlightObjs.length = 0;
  connCylinders.clear();
  $popup.classList.add("hidden");

  // re-add lights & grid
  scene.add(new THREE.AmbientLight(0xffffff, 0.45));
  const s2 = new THREE.DirectionalLight(0xffffff, 0.9);
  s2.position.set(12, 20, 10);
  scene.add(s2);
  const f2 = new THREE.DirectionalLight(0x8888ff, 0.25);
  f2.position.set(-12, -6, -10);
  scene.add(f2);
  const g2 = new THREE.GridHelper(100, 50, 0x222244, 0x1a1a33);
  g2.position.y = -6;
  scene.add(g2);

  // load design
  $loadText.textContent = `Loading ${designPath}…`;
  $loading.classList.remove("hidden");

  let data;
  try {
    const resp = await fetch(designPath);
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    data = await resp.json();
  } catch (err) {
    $loadText.textContent = `Error: ${err.message}`;
    return;
  }
  designData = data;
  $title.textContent = data.design_name ?? "SV Diagrams";
  document.title = `SV Diagrams – ${data.design_name ?? ""}`;

  const modules = data.modules ?? {};
  const instances = data.instances ?? [];
  const connections = data.connections ?? [];
  const groups = data.groups ?? [];
  const tb = data.testbench ?? {};

  // ── compute fan-out for dynamic sizing ──────────────────────────
  const fanOut = {};
  for (const inst of instances) fanOut[inst.name] = 0;
  for (const conn of connections) {
    const f = conn.from?.instance;
    const t = conn.to?.instance;
    if (f && fanOut[f] !== undefined) fanOut[f]++;
    if (t && fanOut[t] !== undefined) fanOut[t]++;
  }
  const maxFan = Math.max(1, ...Object.values(fanOut));

  // ── create instance cuboids ─────────────────────────────────────
  const instMap = {};  // name → { group, mesh, position, sx, sy, sz }
  for (const inst of instances) {
    const mod = modules[inst.module] ?? {};
    const hexStr = mod.color ?? "#42A5F5";
    const hex = parseInt(hexStr.replace("#", ""), 16);

    // dynamic scale based on port count & fan-out
    const ports = mod.ports ?? [];
    const portCount = ports.length;
    const fo = fanOut[inst.name] ?? 0;
    const portScale = Math.min(K.MAX_SCALE, K.MIN_SCALE + portCount * 0.04);
    const foScale = 1 + (fo / maxFan) * 0.4;
    const scale = Math.max(K.MIN_SCALE, Math.min(K.MAX_SCALE, portScale * foScale));

    const { group, mesh, sx, sy, sz } = instanceCuboid(inst, hex, scale);
    scene.add(group);

    instMap[inst.name] = { group, mesh, position: inst.position, sx, sy, sz, module: inst.module };

    // register click target
    clickableObjects.push(mesh);
    objectMeta.set(mesh, { type: "instance", data: { instance: inst, module: mod } });
  }

  // ── create groups (composable blocks – nested solid enclosures) ───
  // Sort by member count descending so outer groups render first for proper depth
  const sortedGroups = [...groups].sort(
    (a, b) => (b.instances?.length ?? 0) - (a.instances?.length ?? 0)
  );

  for (let gi = 0; gi < sortedGroups.length; gi++) {
    const grp = sortedGroups[gi];
    const grpInstances = (grp.instances ?? [])
      .map(n => instMap[n])
      .filter(Boolean);
    if (grpInstances.length === 0) continue;

    // Compute bounds from member cubes (include their sizes)
    const pad = grp.padding ?? 2;
    let xMin = Infinity, xMax = -Infinity;
    let yMin = Infinity, yMax = -Infinity;
    let zMin = Infinity, zMax = -Infinity;
    for (const g of grpInstances) {
      const p = g.position;
      const hs = (g.sx ?? K.BASE_CUBE) / 2;
      const hh = (g.sy ?? K.BASE_CUBE) / 2;
      const hd = (g.sz ?? K.BASE_CUBE) / 2;
      xMin = Math.min(xMin, (p.x ?? 0) - hs);
      xMax = Math.max(xMax, (p.x ?? 0) + hs);
      yMin = Math.min(yMin, (p.y ?? 0) - hh);
      yMax = Math.max(yMax, (p.y ?? 0) + hh);
      zMin = Math.min(zMin, (p.z ?? 0) - hd);
      zMax = Math.max(zMax, (p.z ?? 0) + hd);
    }
    xMin -= pad; xMax += pad;
    yMin -= pad; yMax += pad;
    zMin -= pad; zMax += pad;

    const cx = (xMin + xMax) / 2;
    const cy = (yMin + yMax) / 2;
    const cz = (zMin + zMax) / 2;
    const w = xMax - xMin;
    const h = Math.max(yMax - yMin, K.MIN_GROUP_H);
    const d = zMax - zMin;

    // depth: outer groups (more members) get lower depth number
    const depth = gi;
    const grpColor = parseInt((grp.color ?? "#546E7A").replace("#", ""), 16);
    const { group: blockGroup, mesh: blockMesh } = composableBlock(cx, cy, cz, w, h, d, grpColor, depth);
    scene.add(blockGroup);

    // group label at top of the box – LOD scales with group size
    const lodScale = grpInstances.length >= instances.length * 0.5 ? 2.0 : 1.2;
    const label = makeLabel(grp.name, "group-label");
    label.position.set(cx, yMax + 1.2, cz);
    scene.add(label);
    lodObjects.push({ obj: label, maxDist: K.LOD_DIST * lodScale });

    // register click target on the composable block mesh
    clickableObjects.push(blockMesh);
    objectMeta.set(blockMesh, { type: "group", data: grp });
  }

  // ── create connections (bundled cylinders) ──────────────────────
  const obstacles = instances.map(inst => ({
    x: inst.position.x, y: inst.position.y, z: inst.position.z,
    hw: K.BASE_CUBE, hh: K.BASE_CUBE,
  }));

  for (const conn of connections) {
    const fromInst = instMap[conn.from?.instance];
    const toInst = instMap[conn.to?.instance];
    if (!fromInst || !toInst) continue;

    const fp = fromInst.position;
    const tp = toInst.position;

    // Route the connection
    const waypoints = routeConnection(
      fp.x, fp.y, fp.z,
      tp.x, tp.y, tp.z,
      obstacles
    );

    // Determine colour
    const connType = conn.type ?? "signal";
    let color;
    if (conn.color) {
      color = parseInt(conn.color.replace("#", ""), 16);
    } else if (connType === "clock") {
      color = K.CLK_COL;
    } else if (connType === "reset") {
      color = K.RST_COL;
    } else if (connType === "tlm") {
      color = K.TLM_COL;
    } else if (connType === "hierarchy") {
      color = K.HIER_COL;
    } else {
      color = K.SIG_COL;
    }

    const signals = conn.signals ?? [];
    const numSigs = signals.length;
    const connKey = conn.id ?? `${conn.from?.instance}_to_${conn.to?.instance}`;
    const cyls = [];

    // Draw bundled cylinder for each segment
    for (let i = 0; i < waypoints.length - 1; i++) {
      const cyl = bundleCylinder(waypoints[i], waypoints[i + 1], color, numSigs);
      scene.add(cyl);
      cyls.push(cyl);

      // hit zone for clicking
      const hz = hitZone(waypoints[i], waypoints[i + 1]);
      scene.add(hz);
      clickableObjects.push(hz);
      objectMeta.set(hz, { type: "connection", data: conn });
    }

    // Track cylinders for highlight (store original opacity for restore)
    connCylinders.set(connKey, { cylinders: cyls, originalColor: color, originalOpacity: 0.45, conn });

    // signal count label at midpoint
    if (numSigs > 1) {
      const midIdx = Math.floor(waypoints.length / 2);
      const mp = waypoints[midIdx];
      const lbl = makeLabel(`×${numSigs}`, "bus-label");
      lbl.position.set(mp[0], mp[1] + 1, mp[2]);
      scene.add(lbl);
      lodObjects.push({ obj: lbl, maxDist: K.LOD_DIST * 0.7 });
    }
  }

  // ── testbench enclosure (composable block – outermost container) ─
  if (instances.length > 0) {
    const allBounds = computeBounds(instances, 8);
    const cx = (allBounds.xMin + allBounds.xMax) / 2;
    const cy = (allBounds.yMin + allBounds.yMax) / 2;
    const cz = (allBounds.zMin + allBounds.zMax) / 2;
    const w = allBounds.xMax - allBounds.xMin;
    const h = Math.max(allBounds.yMax - allBounds.yMin, 6);
    const d = allBounds.zMax - allBounds.zMin;

    const { group: tbGroup } = composableBlock(cx, cy, cz, w, h, d, K.TB_COL, 0);
    scene.add(tbGroup);

    const tbName = tb.module_name ?? data.design_name ?? "Testbench";
    const tbLabel = makeLabel(tbName, "group-label");
    tbLabel.position.set(cx, cy + h / 2 + 1.5, cz);
    scene.add(tbLabel);
    lodObjects.push({ obj: tbLabel, maxDist: K.LOD_DIST * 2.5 });
  }

  // ── global signals (clock/reset rails) ──────────────────────────
  const globalSigs = tb.global_signals ?? [];
  for (const gs of globalSigs) {
    const gsColor = parseInt((gs.color ?? "#FFFFFF").replace("#", ""), 16);
    const face = gs.face ?? "bottom";
    const yOff = face === "bottom" ? -3 : 3;

    // Rail across all instances
    const xs = instances.map(i => i.position.x);
    if (xs.length === 0) continue;
    const minX = Math.min(...xs) - 6;
    const maxX = Math.max(...xs) + 6;
    const railZ = Math.max(...instances.map(i => i.position.z)) + 8;
    const railY = yOff;

    const rail = dashedLine(
      [[minX, railY, railZ], [maxX, railY, railZ]],
      gsColor
    );
    scene.add(rail);

    // Stubs from rail to each instance
    for (const inst of instances) {
      const stub = solidLine(
        [[inst.position.x, railY, railZ], [inst.position.x, railY, inst.position.z]],
        gsColor
      );
      scene.add(stub);
    }

    // Label
    const lbl = makeLabel(gs.name, "rail-label");
    lbl.element.style.color = gs.color ?? "#FFFFFF";
    lbl.position.set(maxX + 2, railY, railZ);
    scene.add(lbl);
  }

  // ── fit camera ──────────────────────────────────────────────────
  if (instances.length > 0) {
    const b = computeBounds(instances, 10);
    const cx = (b.xMin + b.xMax) / 2;
    const cy = (b.yMin + b.yMax) / 2;
    const cz = (b.zMin + b.zMax) / 2;
    const span = Math.max(b.xMax - b.xMin, b.zMax - b.zMin, 20);
    camera.position.set(cx, cy + span * 0.6, cz + span * K.CAM_DIST);
    controls.target.set(cx, cy, cz);
    controls.update();
  }

  $loading.classList.add("hidden");
}

/* ─── click / interaction ────────────────────────────────────────────── */

const raycaster = new THREE.Raycaster();
raycaster.params.Line = { threshold: 0.5 };
const pointer = new THREE.Vector2();

function onCanvasClick(event) {
  // Convert mouse to NDC
  const rect = canvas.getBoundingClientRect();
  pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
  pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;

  raycaster.setFromCamera(pointer, camera);
  const hits = raycaster.intersectObjects(clickableObjects, false);

  clearHighlight();

  if (hits.length === 0) {
    $popup.classList.add("hidden");
    return;
  }

  // Prioritise: instance > connection > group (prefer precise targets)
  let chosen = null;
  for (const h of hits) {
    const m = objectMeta.get(h.object);
    if (!m) continue;
    if (m.type === "instance") { chosen = { hit: h, meta: m }; break; }
    if (m.type === "connection" && (!chosen || chosen.meta.type === "group")) {
      chosen = { hit: h, meta: m };
    }
    if (m.type === "group" && !chosen) {
      chosen = { hit: h, meta: m };
    }
  }
  if (!chosen) return;
  const meta = chosen.meta;

  if (meta.type === "instance") {
    showInstanceInfo(meta.data.instance, meta.data.module);
    highlightInstance(meta.data.instance.name);
  } else if (meta.type === "connection") {
    showConnectionInfo(meta.data);
    highlightConnection(meta.data);
  } else if (meta.type === "group") {
    showGroupInfo(meta.data);
    highlightGroup(meta.data);
  }
}

/* ─── highlight helpers ──────────────────────────────────────────────── */

function clearHighlight() {
  for (const obj of currentHighlightObjs) {
    scene.remove(obj);
    if (obj.geometry) obj.geometry.dispose();
    if (obj.material) obj.material.dispose();
  }
  currentHighlightObjs = [];

  // Restore connection cylinder original appearance
  for (const [, entry] of connCylinders) {
    for (const cyl of entry.cylinders) {
      cyl.material.opacity = entry.originalOpacity;
      cyl.material.emissive?.setHex(0x000000);
      cyl.material.emissiveIntensity = 0;
    }
  }
}

function highlightInstance(instName) {
  // Find the instance group and create a glow
  for (const child of scene.children) {
    if (child.userData?.instanceName === instName) {
      const pos = child.position;
      const s = (child.userData.scale ?? 1) * K.BASE_CUBE + 0.5;
      const glowGeo = new THREE.BoxGeometry(s, s, s);
      const glowMat = new THREE.MeshBasicMaterial({
        color: 0xffffff, transparent: true, opacity: 0.12, side: THREE.BackSide,
      });
      const glow = new THREE.Mesh(glowGeo, glowMat);
      glow.position.copy(pos);
      scene.add(glow);
      currentHighlightObjs.push(glow);

      // wireframe highlight
      const wireGeo = new THREE.EdgesGeometry(glowGeo);
      const wireMat = new THREE.LineBasicMaterial({ color: 0x90caf9 });
      const wire = new THREE.LineSegments(wireGeo, wireMat);
      wire.position.copy(pos);
      scene.add(wire);
      currentHighlightObjs.push(wire);
    }
  }

  // Highlight connections involving this instance
  addConnectionHighlights(instName);
}

function addConnectionHighlights(instName) {
  if (!designData) return;
  for (const conn of (designData.connections ?? [])) {
    if (conn.from?.instance === instName || conn.to?.instance === instName) {
      // Brighten connection cylinders
      const connKey = conn.id ?? `${conn.from?.instance}_to_${conn.to?.instance}`;
      const entry = connCylinders.get(connKey);
      if (entry) {
        for (const cyl of entry.cylinders) {
          cyl.material.opacity = 0.9;
          cyl.material.emissive.setHex(0xffffff);
          cyl.material.emissiveIntensity = 0.3;
        }
      }

      // Find the connected instance and add a subtle glow
      const otherName = conn.from?.instance === instName
        ? conn.to?.instance : conn.from?.instance;
      for (const child of scene.children) {
        if (child.userData?.instanceName === otherName) {
          const pos = child.position;
          const s = (child.userData.scale ?? 1) * K.BASE_CUBE + 0.3;
          const g = new THREE.BoxGeometry(s, s, s);
          const m = new THREE.MeshBasicMaterial({
            color: 0xffc107, transparent: true, opacity: 0.08, side: THREE.BackSide,
          });
          const mesh = new THREE.Mesh(g, m);
          mesh.position.copy(pos);
          scene.add(mesh);
          currentHighlightObjs.push(mesh);
        }
      }
    }
  }
}

function highlightConnection(conn) {
  // Brighten connection cylinders for this connection
  const connKey = conn.id ?? `${conn.from?.instance}_to_${conn.to?.instance}`;
  const entry = connCylinders.get(connKey);
  if (entry) {
    for (const cyl of entry.cylinders) {
      cyl.material.opacity = 0.95;
      cyl.material.emissive.setHex(0xffffff);
      cyl.material.emissiveIntensity = 0.4;
    }
  }

  // Highlight both endpoints
  if (conn.from?.instance) highlightInstance(conn.from.instance);
  if (conn.to?.instance) {
    for (const child of scene.children) {
      if (child.userData?.instanceName === conn.to.instance) {
        const pos = child.position;
        const s = (child.userData.scale ?? 1) * K.BASE_CUBE + 0.5;
        const g = new THREE.BoxGeometry(s, s, s);
        const m = new THREE.MeshBasicMaterial({
          color: 0x90caf9, transparent: true, opacity: 0.12, side: THREE.BackSide,
        });
        const mesh = new THREE.Mesh(g, m);
        mesh.position.copy(pos);
        scene.add(mesh);
        currentHighlightObjs.push(mesh);
      }
    }
  }
}

function highlightGroup(grp) {
  for (const instName of (grp.instances ?? [])) {
    for (const child of scene.children) {
      if (child.userData?.instanceName === instName) {
        const pos = child.position;
        const s = (child.userData.scale ?? 1) * K.BASE_CUBE + 0.3;
        const g = new THREE.BoxGeometry(s, s, s);
        const m = new THREE.MeshBasicMaterial({
          color: 0xce93d8, transparent: true, opacity: 0.1, side: THREE.BackSide,
        });
        const mesh = new THREE.Mesh(g, m);
        mesh.position.copy(pos);
        scene.add(mesh);
        currentHighlightObjs.push(mesh);
      }
    }
  }
}

/* ─── popup content builders ─────────────────────────────────────────── */

function showInstanceInfo(inst, mod) {
  $popTitle.textContent = inst.name;
  let html = "";

  // Module info
  html += `<p class="section-title">Module</p>`;
  html += `<p>${mod.description ?? inst.module}</p>`;

  // Classes (for VIP)
  const classes = mod.classes ?? inst.info?.classes;
  if (classes && classes.length > 0) {
    html += `<p class="section-title">Classes (${mod.class_count ?? classes.length})</p>`;
    html += `<div class="signal-list">`;
    for (const c of classes) {
      html += `<div>${c}</div>`;
    }
    if ((mod.class_count ?? 0) > classes.length) {
      html += `<div style="color:#78909C">… and ${mod.class_count - classes.length} more</div>`;
    }
    html += `</div>`;
  }

  // Port table (for RTL)
  const ports = mod.ports ?? [];
  if (ports.length > 0) {
    html += `<p class="section-title">Ports (${ports.length})</p>`;
    html += `<table><tr><th>Name</th><th>Dir</th><th>Width</th></tr>`;
    for (const p of ports.slice(0, 25)) {
      html += `<tr><td>${p.name}</td><td>${p.direction ?? ""}</td><td>${p.width ?? 1}</td></tr>`;
    }
    if (ports.length > 25) {
      html += `<tr><td colspan="3" style="color:#78909C">… ${ports.length - 25} more</td></tr>`;
    }
    html += `</table>`;
  }

  // Instance info (metadata from blockify)
  const info = inst.info ?? {};
  if (info.num_ports !== undefined) {
    html += `<p class="section-title">RTL Details</p>`;
    html += `<table>`;
    html += `<tr><td>Ports</td><td>${info.num_ports} (${info.num_inputs}in / ${info.num_outputs}out)</td></tr>`;
    html += `<tr><td>Input bits</td><td>${info.total_input_bits}</td></tr>`;
    html += `<tr><td>Output bits</td><td>${info.total_output_bits}</td></tr>`;
    if (info.num_registers) html += `<tr><td>Registers</td><td>${info.num_registers}</td></tr>`;
    if (info.num_wires) html += `<tr><td>Wires</td><td>${info.num_wires}</td></tr>`;
    if (info.has_fsm) html += `<tr><td>FSM</td><td>Yes (potential)</td></tr>`;
    if (info.compilation) html += `<tr><td>Compilation</td><td>${info.compilation}</td></tr>`;
    html += `</table>`;
  }

  if (info.signal_count !== undefined) {
    html += `<p class="section-title">Interface Signals (${info.signal_count})</p>`;
    html += `<div class="signal-list">`;
    for (const s of (info.signals ?? [])) {
      html += `<div>${s.name} : ${s.type}</div>`;
    }
    html += `</div>`;
  }

  // Connected signals
  if (designData) {
    const myConns = (designData.connections ?? []).filter(
      c => c.from?.instance === inst.name || c.to?.instance === inst.name
    );
    if (myConns.length > 0) {
      html += `<p class="section-title">Connections (${myConns.length})</p>`;
      for (const c of myConns.slice(0, 10)) {
        const dir = c.from?.instance === inst.name ? "→" : "←";
        const other = c.from?.instance === inst.name ? c.to?.instance : c.from?.instance;
        const nSigs = (c.signals ?? []).length;
        html += `<div><span class="highlight-tag" style="background:rgba(144,202,249,.15)">${dir} ${other}</span> ${nSigs} signal(s)</div>`;
      }
      if (myConns.length > 10) {
        html += `<div style="color:#78909C">… ${myConns.length - 10} more connections</div>`;
      }
    }
  }

  $popBody.innerHTML = html;
  $popup.classList.remove("hidden");
}

function showConnectionInfo(conn) {
  $popTitle.textContent = conn.description ?? conn.id ?? "Connection";
  let html = "";

  html += `<p class="section-title">Route</p>`;
  html += `<p><span class="highlight-tag" style="background:rgba(144,202,249,.15)">${conn.from?.instance ?? "?"}</span>`;
  html += `.${conn.from?.port ?? ""} → `;
  html += `<span class="highlight-tag" style="background:rgba(144,202,249,.15)">${conn.to?.instance ?? "?"}</span>`;
  html += `.${conn.to?.port ?? ""}</p>`;
  html += `<p>Type: <strong>${conn.type ?? "signal"}</strong></p>`;

  const signals = conn.signals ?? [];
  if (signals.length > 0) {
    html += `<p class="section-title">Bundled Signals (${signals.length})</p>`;
    html += `<table><tr><th>Signal</th><th>Width</th><th>Mapping</th></tr>`;
    for (const s of signals.slice(0, 40)) {
      const w = s.width ?? 1;
      const range = w > 1 ? `[${w - 1}:0]` : "[0]";
      html += `<tr><td style="font-family:monospace;font-size:11px">${s.name}</td>`;
      html += `<td>${w}</td>`;
      html += `<td style="font-size:11px;color:#78909C">${conn.from?.instance}.${s.name} → ${conn.to?.instance}.${s.name}</td></tr>`;
    }
    if (signals.length > 40) {
      html += `<tr><td colspan="3" style="color:#78909C">… ${signals.length - 40} more</td></tr>`;
    }
    html += `</table>`;
  }

  $popBody.innerHTML = html;
  $popup.classList.remove("hidden");
}

function showGroupInfo(grp) {
  $popTitle.textContent = grp.name ?? "Group";
  let html = "";

  html += `<p>${grp.description ?? ""}</p>`;
  html += `<p class="section-title">Instances (${(grp.instances ?? []).length})</p>`;
  html += `<ul>`;
  for (const n of (grp.instances ?? [])) {
    html += `<li>${n}</li>`;
  }
  html += `</ul>`;

  $popBody.innerHTML = html;
  $popup.classList.remove("hidden");
}

/* ─── overview panel ─────────────────────────────────────────────────── */

function buildOverview() {
  if (!designData) return;
  const d = designData;
  $ovTitle.textContent = d.design_name ?? "Design Overview";
  let html = "";

  html += `<p>${d.description ?? ""}</p>`;

  if (d.summary) {
    html += `<h3>Summary</h3><table>`;
    for (const [k, v] of Object.entries(d.summary)) {
      html += `<tr><td>${k.replace(/_/g, " ")}</td><td>${v}</td></tr>`;
    }
    html += `</table>`;
  }

  if (d.protocol) html += `<p><strong>Protocol:</strong> ${d.protocol}</p>`;
  if (d.data_width) html += `<p><strong>Data Width:</strong> ${d.data_width} bits</p>`;
  if (d.source_repo) html += `<p><strong>Source:</strong> <a href="${d.source_repo}" target="_blank" style="color:#90caf9">${d.source_repo}</a></p>`;

  // Instances legend
  const modules = d.modules ?? {};
  html += `<h3>Modules</h3>`;
  html += `<table><tr><th></th><th>Module</th><th>Description</th></tr>`;
  for (const [key, mod] of Object.entries(modules)) {
    const color = mod.color ?? "#42A5F5";
    html += `<tr><td><span class="swatch" style="background:${color}"></span></td>`;
    html += `<td>${key}</td><td>${mod.description ?? ""}</td></tr>`;
  }
  html += `</table>`;

  // Instances
  const instances = d.instances ?? [];
  html += `<h3>Instances (${instances.length})</h3><ul>`;
  for (const inst of instances) {
    html += `<li><strong>${inst.name}</strong> (${inst.module})</li>`;
  }
  html += `</ul>`;

  // Connections
  const connections = d.connections ?? [];
  html += `<h3>Connections (${connections.length})</h3><ul>`;
  for (const conn of connections.slice(0, 15)) {
    html += `<li>${conn.from?.instance ?? "?"} → ${conn.to?.instance ?? "?"} (${(conn.signals ?? []).length} signals)</li>`;
  }
  if (connections.length > 15) {
    html += `<li>… ${connections.length - 15} more</li>`;
  }
  html += `</ul>`;

  $ovBody.innerHTML = html;
  $overview.classList.remove("hidden");
}

/* ─── animation loop ─────────────────────────────────────────────────── */

const tmpVec = new THREE.Vector3();

function animate() {
  requestAnimationFrame(animate);
  controls.update();

  // LOD: hide distant labels
  const camPos = camera.position;
  for (const entry of lodObjects) {
    if (entry.obj.parent) {
      const worldPos = entry.obj.parent.localToWorld
        ? entry.obj.getWorldPosition(tmpVec)
        : entry.obj.position;
      const d = camPos.distanceTo(worldPos);
      entry.obj.visible = d <= entry.maxDist;
    }
  }

  renderer.render(scene, camera);
  labelRenderer.render(scene, camera);
}

/* ─── events ─────────────────────────────────────────────────────────── */

canvas.addEventListener("click", onCanvasClick);

document.getElementById("btn-overview").addEventListener("click", buildOverview);
document.getElementById("close-overview").addEventListener("click", () => {
  $overview.classList.add("hidden");
});

document.getElementById("close-popup").addEventListener("click", () => {
  $popup.classList.add("hidden");
  clearHighlight();
});

$select.addEventListener("change", () => {
  const val = $select.value;
  if (val) buildScene(`metadata/${val}`);
});

window.addEventListener("resize", () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
  labelRenderer.setSize(window.innerWidth, window.innerHeight);
});

// Popup dragging
let dragState = null;
document.getElementById("popup-handle").addEventListener("mousedown", (e) => {
  dragState = {
    startX: e.clientX,
    startY: e.clientY,
    origRight: parseInt(getComputedStyle($popup).right),
    origBottom: parseInt(getComputedStyle($popup).bottom),
  };
  e.preventDefault();
});
window.addEventListener("mousemove", (e) => {
  if (!dragState) return;
  const dx = e.clientX - dragState.startX;
  const dy = e.clientY - dragState.startY;
  $popup.style.right = (dragState.origRight - dx) + "px";
  $popup.style.bottom = (dragState.origBottom - dy) + "px";
});
window.addEventListener("mouseup", () => { dragState = null; });

/* ─── boot ───────────────────────────────────────────────────────────── */

async function init() {
  // Load design index
  try {
    const resp = await fetch("metadata/index.json");
    const idx = await resp.json();
    for (const d of (idx.designs ?? [])) {
      const opt = document.createElement("option");
      opt.value = d.file;
      opt.textContent = `${d.name} – ${d.description?.substring(0, 50) ?? ""}`;
      $select.appendChild(opt);
    }
  } catch {
    // No index; add fallback options
    for (const f of ["uvc_axi4.json", "uvc_ahb.json", "uvc_apb.json", "uvc_uart.json", "dma_axi32.json", "dma_axi64.json"]) {
      const opt = document.createElement("option");
      opt.value = f;
      opt.textContent = f.replace(".json", "");
      $select.appendChild(opt);
    }
  }

  // Auto-load first design
  if ($select.options.length > 1) {
    $select.selectedIndex = 1;
    await buildScene(`metadata/${$select.value}`);
  } else {
    $loading.classList.add("hidden");
  }

  animate();
}

init();
